import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { buildAgentTools } from '@/agent/agentTools.js';
import type { RequestContext } from '@/context.js';
import { buildBackgroundTools } from '@/tools/background.js';
import { buildCalculatorTools } from '@/tools/calculator.js';
import { buildDateTools } from '@/tools/dates.js';
import { buildDelegateTools } from '@/tools/delegate.js';
import { buildFinanceTools } from '@/tools/finance.js';
import { buildInteractionTools } from '@/tools/interaction.js';
import { buildMemoryTools } from '@/tools/memory.js';
import type { KindedToolSet } from '@/tools/types.js';

const OUTPUT_PATH = resolve(import.meta.dirname, '../../frontend/src/lib/chat/toolManifest.generated.ts');

const stubContext: RequestContext = { timezone: 'UTC', lang: 'en' };

function collectAllTools(): KindedToolSet {
  return {
    ...buildDateTools(stubContext),
    ...buildFinanceTools(stubContext),
    ...buildMemoryTools(),
    ...buildCalculatorTools(),
    ...buildInteractionTools(),
    ...buildDelegateTools(stubContext, 'AUTONOMOUS'),
    ...buildBackgroundTools(stubContext),
    ...buildAgentTools('manifest-generation'),
  };
}

function renderManifest(toolSet: KindedToolSet): string {
  const names = Object.keys(toolSet).sort();

  const manifestEntries = names
    .map((name) => {
      const { invalidates, patchesForm } = toolSet[name].ui;
      const domains = invalidates.map((domain) => JSON.stringify(domain)).join(', ');
      return `  ${name}: { invalidates: [${domains}], patchesForm: ${patchesForm === true} },`;
    })
    .join('\n');

  const labelEntries = (lang: 'en' | 'es') =>
    names.map((name) => `    ${name}: ${JSON.stringify(toolSet[name].ui.label[lang])},`).join('\n');

  return `// AUTO-GENERATED by chatbot/scripts/generate-tool-manifest.ts — run \`pnpm gen:tools\` in chatbot/. Do not edit.
import type { CacheDomain } from '@/lib/cacheInvalidation';

export interface ChatToolManifestEntry {
  invalidates: readonly CacheDomain[];
  patchesForm: boolean;
}

export const CHAT_TOOL_MANIFEST = {
${manifestEntries}
} as const satisfies Record<string, ChatToolManifestEntry>;

export type ChatToolName = keyof typeof CHAT_TOOL_MANIFEST;

export const chatToolLabels: Record<'en' | 'es', Record<ChatToolName, string>> = {
  en: {
${labelEntries('en')}
  },
  es: {
${labelEntries('es')}
  },
};
`;
}

writeFileSync(OUTPUT_PATH, renderManifest(collectAllTools()));
console.log(`Tool manifest written to ${OUTPUT_PATH}`);
