package com.mypaybyday.enums;

public enum InternalErrorCode {
	UNEXPECTED,
	ENCRYPTION_FAILED,
	DECRYPTION_FAILED,
	ENCRYPTION_INIT_FAILED,
	HASHING_FAILED,
	PROMPT_LOAD_FAILED,
	JSON_SERIALIZATION_FAILED,
	JSON_DESERIALIZATION_FAILED,
	FILE_IO_FAILED,
	AI_INVOCATION_FAILED
}
