quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:mypaybyday.db
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Swagger UI / OpenAPI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.smallrye-openapi.path=/openapi


# quarkus.langchain4j.ollama.chat-model.base-url=http://localhost:11434
# quarkus.langchain4j.ollama.chat-model.model-id=qwen:1.5b
# quarkus.rest-client.langchain4j-ollama.timeout=60000