import { tool } from 'ai';
import { z } from 'zod';
import type { RequestContext } from '@/context.js';
import { conversationMemory } from '@/memory/conversation.js';
import { conversationRecap } from '@/memory/recap.js';
import type { KindedToolSet } from '@/tools/types.js';

function matchesQuery(haystack: string, query: string | null | undefined): boolean {
  if (!query) return true;
  return haystack.toLowerCase().includes(query.toLowerCase());
}

/**
 * Read-only tools that let the agent look back at the user's other conversations — to recover context
 * the user refers to ("like we discussed last time") without them having to repeat it. The current
 * conversation is excluded (the model already has it in context), and agent-task threads are already
 * filtered out by conversationMemory.listAll.
 */
export function buildConversationTools(ctx: RequestContext): KindedToolSet {
  const currentChatId = ctx.chatId;
  const lang = ctx.lang;

  return {
    listPreviousChats: {
      kind: 'READ',
      ui: { invalidates: [], label: { en: 'Looking through past chats...', es: 'Revisando chats anteriores...' } },
      tool: tool({
        description:
          'List the user\'s previous conversations (most recent first), optionally filtered by a search term matched ' +
          'against each chat\'s title and preview. Returns a chatId for each; pass it to readPreviousChat to get a ' +
          'summary of that conversation. The current conversation is never included.',
        inputSchema: z.object({ query: z.string().nullish() }),
        execute: async ({ query }) => {
          return conversationMemory
            .listAll()
            .filter((chat) => chat.chatId !== currentChatId)
            .filter((chat) => matchesQuery(`${chat.title ?? ''} ${chat.preview}`, query))
            .map((chat) => ({
              chatId: chat.chatId,
              title: chat.title,
              preview: chat.preview,
              lastMessageAt: chat.lastMessageAt,
              messageCount: chat.messageCount,
            }));
        },
      }),
    },

    readPreviousChat: {
      kind: 'READ',
      ui: { invalidates: [], label: { en: 'Reading a past chat...', es: 'Leyendo un chat anterior...' } },
      tool: tool({
        description:
          'Get a concise summary of one of the user\'s previous conversations by its chatId (from listPreviousChats). ' +
          'Returns a compact recap (key facts, decisions, IDs, amounts, pending items) generated by a fast model and ' +
          'cached, not the full transcript — so recalling an earlier chat costs little context. Use it to recover ' +
          'details the user refers to from a past conversation.',
        inputSchema: z.object({ chatId: z.string().min(1) }),
        execute: async ({ chatId }) => {
          if (chatId === currentChatId) {
            return { error: 'That is the current conversation, which you already have in context.' };
          }
          const result = await conversationRecap.getOrGenerate(chatId, lang);
          if (!result) {
            return { error: `No conversation found for chatId "${chatId}".` };
          }
          return {
            chatId,
            title: conversationMemory.getTitle(chatId),
            messageCount: result.messageCount,
            summary: result.recap,
          };
        },
      }),
    },
  };
}
