import { tool } from 'ai';
import { z } from 'zod';
import { BackendError, createApiClient, unwrap, type ApiClient } from '@/backend/client.js';
import {
  botEventGroupInputSchema,
  botInstallmentPlanInputSchema,
  botPaymentPlanItemPatchSchema,
  botPaymentPlanPatchSchema,
  botRecurringPlanInputSchema,
  NumericId,
} from '@/bot/dto.js';
import type { RequestContext } from '@/context.js';
import type { CacheDomain, KindedToolSet } from '@/tools/types.js';

const PLAN_MUTATION_DOMAINS: readonly CacheDomain[] = ['paymentPlans'];
const PLAN_LINK_DOMAINS: readonly CacheDomain[] = ['paymentPlans', 'events', 'drafts'];

type PaymentPlan = Awaited<ReturnType<typeof fetchPlan>>;
type PaymentPlanItem = NonNullable<PaymentPlan['items']>[number];

async function safe<T>(fn: () => Promise<T>): Promise<T | { error: string }> {
  try {
    return await fn();
  } catch (e) {
    const message = e instanceof BackendError ? e.message : (e as Error).message;
    return { error: message };
  }
}

function fetchPlan(client: ApiClient, planId: number) {
  return unwrap(client.GET('/payment-plans/{id}', { params: { path: { id: planId } } }));
}

/**
 * GROUP and CUSTOM plans are composed by hand, so their items can be created and deleted.
 * INSTALLMENT and RECURRING schedules are generated by the backend, which rejects both.
 */
function isUserComposedPlan(plan: PaymentPlan): boolean {
  return plan.planType === 'CUSTOM' || plan.planType === 'GROUP';
}

function findItem(plan: PaymentPlan, itemId: number): PaymentPlanItem | undefined {
  return (plan.items ?? []).find((item) => item.id === itemId);
}

function nextInstallmentNumber(plan: PaymentPlan): number {
  return (plan.items ?? []).reduce((max, item) => Math.max(max, item.installmentNumber ?? 0), 0) + 1;
}

/**
 * The backend replaces a plan wholesale on PUT, so every partial edit has to be merged onto the
 * current plan first. Sending only the changed fields would silently blank out everything else.
 */
function mergePlanPatch(plan: PaymentPlan, patch: z.infer<typeof botPaymentPlanPatchSchema>) {
  return {
    name: patch.name ?? plan.name,
    description: patch.description ?? plan.description ?? undefined,
    planType: plan.planType,
    status: patch.status ?? plan.status,
    startDate: patch.startDate ?? plan.startDate,
    frequency: patch.frequency ?? plan.frequency,
    totalInstallments: patch.totalInstallments ?? plan.totalInstallments ?? undefined,
    totalAmount: patch.totalAmount ?? plan.totalAmount ?? undefined,
    installmentAmount: patch.installmentAmount ?? plan.installmentAmount ?? undefined,
    isAutomated: patch.isAutomated ?? plan.isAutomated,
    autoCreateDraft: plan.autoCreateDraft,
    categoryId: patch.categoryId ?? plan.category?.id ?? undefined,
    tagIds: patch.tagIds ?? (plan.tags ?? []).map((tag) => tag.id).filter((id): id is number => id != null),
    originNodeId: patch.originNodeId ?? plan.originNode?.id ?? undefined,
    destinationNodeId: patch.destinationNodeId ?? plan.destinationNode?.id ?? undefined,
  };
}

/**
 * Same wholesale-replace rule applies to items, and it extends to their links: a PUT without
 * eventId/draftId unlinks the item. Every item edit therefore carries the current link forward
 * unless the caller is explicitly changing it.
 */
function mergeItemPatch(
  item: PaymentPlanItem,
  patch: {
    expectedDate?: string | null;
    expectedAmount?: number | null;
    installmentNumber?: number | null;
    itemStatus?: PaymentPlanItem['itemStatus'] | null;
    eventId?: number | null;
    draftId?: number | null;
  },
  links: { keepCurrent: boolean },
) {
  const currentEventId = links.keepCurrent ? item.eventId ?? undefined : undefined;
  const currentDraftId = links.keepCurrent ? item.draftId ?? undefined : undefined;

  return {
    installmentNumber: patch.installmentNumber ?? item.installmentNumber,
    expectedDate: patch.expectedDate ?? item.expectedDate,
    expectedAmount: patch.expectedAmount ?? item.expectedAmount ?? undefined,
    itemStatus: patch.itemStatus ?? item.itemStatus,
    eventId: patch.eventId ?? currentEventId,
    draftId: patch.draftId ?? currentDraftId,
  };
}

function putItem(client: ApiClient, planId: number, itemId: number, body: ReturnType<typeof mergeItemPatch>) {
  return unwrap(
    client.PUT('/payment-plans/{id}/items/{itemId}', {
      params: { path: { id: planId, itemId } },
      body,
    }),
  );
}

function describePlan(plan: PaymentPlan) {
  const items = plan.items ?? [];
  return {
    id: plan.id,
    name: plan.name,
    description: plan.description ?? undefined,
    planType: plan.planType,
    status: plan.status,
    frequency: plan.frequency,
    startDate: plan.startDate,
    nextDueDate: plan.nextDueDate ?? undefined,
    isAutomated: plan.isAutomated,
    installmentAmount: plan.installmentAmount ?? undefined,
    totalAmount: plan.totalAmount ?? undefined,
    totalInstallments: plan.totalInstallments ?? undefined,
    completedInstallments: plan.completedInstallments,
    paidAmount: plan.paidAmount,
    remainingAmount: plan.remainingAmount,
    category: plan.category?.name,
    tags: (plan.tags ?? []).map((tag) => tag.name),
    canComposeItems: isUserComposedPlan(plan),
    items: items.map((item) => ({
      itemId: item.id,
      installmentNumber: item.installmentNumber,
      expectedDate: item.expectedDate,
      expectedAmount: item.expectedAmount ?? undefined,
      itemStatus: item.itemStatus,
      eventId: item.eventId ?? undefined,
      draftId: item.draftId ?? undefined,
    })),
  };
}

export function buildPaymentPlanTools(ctx: RequestContext): KindedToolSet {
  const client = createApiClient(ctx);

  function createItem(planId: number, body: { installmentNumber: number; expectedDate: string; itemStatus?: PaymentPlanItem['itemStatus']; eventId?: number; draftId?: number }) {
    return unwrap(client.POST('/payment-plans/{id}/items', { params: { path: { id: planId } }, body }));
  }

  /**
   * The backend silently skips an eventId/draftId that does not exist, so the created plan is
   * read back and any id missing from its items is reported rather than leaving the group
   * looking complete.
   */
  function missingGroupMembers(plan: PaymentPlan, eventIds: number[], draftIds: number[]) {
    const linkedEventIds = new Set((plan.items ?? []).map((item) => item.eventId).filter((id): id is number => id != null));
    const linkedDraftIds = new Set((plan.items ?? []).map((item) => item.draftId).filter((id): id is number => id != null));
    return [...eventIds.filter((id) => !linkedEventIds.has(id)), ...draftIds.filter((id) => !linkedDraftIds.has(id))];
  }

  async function resolveTargetItem(plan: PaymentPlan, itemId: number | null | undefined) {
    if (itemId != null) {
      const requested = findItem(plan, itemId);
      if (!requested) throw new BackendError(404, `Payment plan item not found: ${itemId}`);
      return requested;
    }

    const freeItem = (plan.items ?? []).find((item) => item.eventId == null && item.draftId == null);
    if (freeItem) return freeItem;

    if (!isUserComposedPlan(plan)) {
      throw new BackendError(
        400,
        `Plan ${plan.id} ("${plan.name}") has no free cuota left and its schedule is generated by the system, so no item can be added.`,
      );
    }

    return createItem(plan.id, { installmentNumber: nextInstallmentNumber(plan), expectedDate: plan.startDate });
  }

  return {
    // ===================== READ =====================
    listPaymentPlans: {
      kind: 'READ',
      ui: { invalidates: [], label: { en: 'Checking payment plans...', es: 'Consultando planes de pago...' } },
      tool: tool({
        description:
          'List every payment plan the user has, of all four kinds: installment purchases (cuotas), recurring agreements, ' +
          'one-off event groups and hand-built custom schedules. Use it to check installment progress (e.g. 3/12 cuotas), ' +
          'remaining balance, or to find the plan id any other payment-plan tool needs. Each plan reports canComposeItems, ' +
          'which is true when its items may be added or deleted.',
        inputSchema: z.object({}),
        execute: () =>
          safe(async () => {
            const plans = await unwrap(client.GET('/payment-plans'));
            return { plans: plans.map(describePlan) };
          }),
      }),
    },

    getPaymentPlan: {
      kind: 'READ',
      ui: { invalidates: [], label: { en: 'Reading payment plan...', es: 'Leyendo plan de pago...' } },
      tool: tool({
        description:
          'Read one payment plan with its full item list, including which event or draft each item is linked to. ' +
          'Call this before editing items so you know their itemId, number, date and current link.',
        inputSchema: z.object({ planId: NumericId }),
        execute: ({ planId }) => safe(async () => describePlan(await fetchPlan(client, planId))),
      }),
    },

    // ===================== WRITE: one tool per kind of plan =====================
    createEventGroup: {
      kind: 'WRITE',
      ui: { invalidates: PLAN_LINK_DOMAINS, label: { en: 'Creating event group...', es: 'Creando grupo de eventos...' } },
      tool: tool({
        description:
          'Bundle events that happened once into a named group: a trip, a party, a shared purchase. A group has no cadence, ' +
          'no cuota count and no total — it is just a bucket, and its total is the sum of the events inside it. Pass eventIds ' +
          'and/or draftIds to fill it in the same call; use addToPaymentPlan later to add more. This is the tool for ' +
          '"group these expenses", "how much did the Bariloche trip cost", "create a group for the party".',
        inputSchema: botEventGroupInputSchema,
        execute: (input) =>
          safe(async () => {
            const eventIds = input.eventIds ?? [];
            const draftIds = input.draftIds ?? [];
            const plan = await unwrap(
              client.POST('/payment-plans', {
                body: {
                  name: input.name,
                  description: input.description ?? undefined,
                  planType: 'GROUP',
                  startDate: input.date,
                  frequency: 'INSTANT',
                  isAutomated: false,
                  generateItems: false,
                  categoryId: input.categoryId ?? undefined,
                  tagIds: input.tagIds ?? undefined,
                  eventIds: eventIds.length > 0 ? eventIds : undefined,
                  draftIds: draftIds.length > 0 ? draftIds : undefined,
                },
              }),
            );

            const missing = missingGroupMembers(plan, eventIds, draftIds);

            return {
              ...describePlan(plan),
              linkedCount: (plan.items ?? []).length,
              ...(missing.length > 0 && {
                warning: `These ids do not exist and were not linked: ${missing.join(', ')}`,
              }),
            };
          }),
      }),
    },

    createInstallmentPlan: {
      kind: 'WRITE',
      ui: { invalidates: PLAN_MUTATION_DOMAINS, label: { en: 'Creating installment plan...', es: 'Creando plan en cuotas...' } },
      tool: tool({
        description:
          'Create a purchase split into cuotas — "the fridge in 12 cuotas of 5000". The backend pre-generates one item per ' +
          'cuota, spaced by the chosen cadence, so you never add or delete them by hand: as each cuota is paid, attach its ' +
          'event with addToPaymentPlan. Use this only when the number of cuotas is known and finite; for an open-ended ' +
          'agreement use createRecurringPlan.',
        inputSchema: botInstallmentPlanInputSchema,
        execute: (input) =>
          safe(async () => {
            const plan = await unwrap(
              client.POST('/payment-plans', {
                body: {
                  name: input.name,
                  description: input.description ?? undefined,
                  planType: 'INSTALLMENT',
                  startDate: input.startDate,
                  frequency: input.frequency,
                  totalInstallments: input.totalInstallments,
                  installmentAmount: input.installmentAmount,
                  totalAmount: input.totalAmount ?? input.installmentAmount * input.totalInstallments,
                  isAutomated: false,
                  generateItems: true,
                  categoryId: input.categoryId ?? undefined,
                  tagIds: input.tagIds ?? undefined,
                  originNodeId: input.originNodeId ?? undefined,
                  destinationNodeId: input.destinationNodeId ?? undefined,
                },
              }),
            );
            return describePlan(plan);
          }),
      }),
    },

    createRecurringPlan: {
      kind: 'WRITE',
      ui: { invalidates: PLAN_MUTATION_DOMAINS, label: { en: 'Creating recurring plan...', es: 'Creando plan recurrente...' } },
      tool: tool({
        description:
          'Create an open-ended recurring commitment — a subscription like Netflix, or rent. It has a cadence and an amount ' +
          'per cycle but no end and no cuota count, so no items exist up front; each cycle produces one. Use ' +
          'createInstallmentPlan instead when the number of payments is fixed and known.',
        inputSchema: botRecurringPlanInputSchema,
        execute: (input) =>
          safe(async () => {
            const plan = await unwrap(
              client.POST('/payment-plans', {
                body: {
                  name: input.name,
                  description: input.description ?? undefined,
                  planType: 'RECURRING',
                  startDate: input.startDate,
                  frequency: input.frequency,
                  installmentAmount: input.installmentAmount ?? undefined,
                  isAutomated: input.isAutomated ?? false,
                  generateItems: false,
                  categoryId: input.categoryId ?? undefined,
                  tagIds: input.tagIds ?? undefined,
                  originNodeId: input.originNodeId ?? undefined,
                  destinationNodeId: input.destinationNodeId ?? undefined,
                },
              }),
            );
            return describePlan(plan);
          }),
      }),
    },

    updatePaymentPlan: {
      kind: 'WRITE',
      ui: { invalidates: PLAN_MUTATION_DOMAINS, label: { en: 'Updating payment plan...', es: 'Actualizando plan de pago...' } },
      tool: tool({
        description:
          'Edit any existing payment plan. Only the provided fields change; everything else is preserved. Use status to pause ' +
          'a plan, cancel it, or mark it COMPLETED once a group or a set of cuotas is closed. The kind of plan cannot be changed.',
        inputSchema: botPaymentPlanPatchSchema,
        execute: (patch) =>
          safe(async () => {
            const plan = await fetchPlan(client, patch.planId);
            const updated = await unwrap(
              client.PUT('/payment-plans/{id}', { params: { path: { id: patch.planId } }, body: mergePlanPatch(plan, patch) }),
            );
            return describePlan(updated);
          }),
      }),
    },

    // ===================== WRITE: items =====================
    addToPaymentPlan: {
      kind: 'WRITE',
      ui: { invalidates: PLAN_LINK_DOMAINS, label: { en: 'Adding to payment plan...', es: 'Agregando al plan de pago...' } },
      tool: tool({
        description:
          'Attach an existing event or draft to a plan of any kind, and mark that entry as paid. Pass eventId OR draftId, ' +
          'never both. In a group this adds a new entry; in a cuota or recurring plan it fills the first cuota that has no ' +
          'event yet, or the one named by itemId. This is the tool for "add this expense to the trip group" and for ' +
          '"this payment covers cuota 3".',
        inputSchema: z
          .object({
            planId: NumericId,
            eventId: NumericId.nullish(),
            draftId: NumericId.nullish(),
            itemId: NumericId.nullish().describe('The specific entry to fill. Defaults to the first one with no event.'),
          })
          .refine((input) => (input.eventId == null) !== (input.draftId == null), {
            error: 'Pass exactly one of eventId or draftId.',
          }),
        execute: ({ planId, eventId, draftId, itemId }) =>
          safe(async () => {
            const plan = await fetchPlan(client, planId);
            const target = await resolveTargetItem(plan, itemId);
            const updated = await putItem(
              client,
              planId,
              target.id,
              mergeItemPatch(
                target,
                {
                  itemStatus: eventId != null ? 'PAID' : 'DRAFTED',
                  eventId: eventId ?? undefined,
                  draftId: draftId ?? undefined,
                },
                { keepCurrent: false },
              ),
            );
            return {
              ok: true,
              planId,
              planName: plan.name,
              itemId: updated.id,
              installmentNumber: updated.installmentNumber,
              eventId: updated.eventId ?? undefined,
              draftId: updated.draftId ?? undefined,
            };
          }),
      }),
    },

    removeFromPaymentPlan: {
      kind: 'WRITE',
      ui: { invalidates: PLAN_LINK_DOMAINS, label: { en: 'Removing from payment plan...', es: 'Quitando del plan de pago...' } },
      tool: tool({
        description:
          'Take an event or draft out of a plan. The event itself is never deleted. What happens to the entry depends on the ' +
          'kind of plan, and is decided for you: in a group the entry disappears with it, since an entry without an event is ' +
          'meaningless; in a cuota or recurring plan the cuota stays and goes back to pending, because the schedule belongs ' +
          'to the backend. Identify the entry by itemId, or by the eventId/draftId it holds.',
        inputSchema: z.object({
          planId: NumericId,
          itemId: NumericId.nullish(),
          eventId: NumericId.nullish(),
          draftId: NumericId.nullish(),
        }),
        execute: ({ planId, itemId, eventId, draftId }) =>
          safe(async () => {
            const plan = await fetchPlan(client, planId);
            const items = plan.items ?? [];
            const target =
              itemId != null
                ? items.find((item) => item.id === itemId)
                : items.find((item) =>
                    eventId != null ? item.eventId === eventId : draftId != null && item.draftId === draftId,
                  );

            if (!target) return { error: `No entry of plan ${planId} ("${plan.name}") matches the given itemId/eventId/draftId.` };

            if (isUserComposedPlan(plan)) {
              await unwrap(
                client.DELETE('/payment-plans/{id}/items/{itemId}', { params: { path: { id: planId, itemId: target.id } } }),
              );
              return { ok: true, planId, planName: plan.name, itemId: target.id, outcome: 'entry deleted' };
            }

            const updated = await putItem(
              client,
              planId,
              target.id,
              mergeItemPatch(target, { itemStatus: 'PENDING' }, { keepCurrent: false }),
            );
            return {
              ok: true,
              planId,
              planName: plan.name,
              itemId: updated.id,
              installmentNumber: updated.installmentNumber,
              outcome: 'cuota kept and reset to pending',
            };
          }),
      }),
    },

    updatePaymentPlanItem: {
      kind: 'WRITE',
      ui: { invalidates: PLAN_MUTATION_DOMAINS, label: { en: 'Updating plan entry...', es: 'Actualizando cuota del plan...' } },
      tool: tool({
        description:
          'Edit one entry of a plan: its expected date, expected amount, position or status. Any linked event or draft is ' +
          'kept. On cuota and recurring plans the backend ignores date, amount and position changes — the schedule is its own ' +
          '— and applies only the status.',
        inputSchema: botPaymentPlanItemPatchSchema,
        execute: ({ planId, itemId, ...patch }) =>
          safe(async () => {
            const plan = await fetchPlan(client, planId);
            const item = findItem(plan, itemId);
            if (!item) return { error: `Payment plan item not found: ${itemId}` };

            const updated = await putItem(client, planId, itemId, mergeItemPatch(item, patch, { keepCurrent: true }));
            return { ok: true, planId, itemId, installmentNumber: updated.installmentNumber, itemStatus: updated.itemStatus };
          }),
      }),
    },
  } satisfies KindedToolSet;
}
