package com.mypaybyday.entity;

import java.time.LocalDateTime;
import java.util.LinkedHashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.OneToMany;
import jakarta.validation.constraints.NotNull;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * The accounting envelope generated by an {@link FinanceEventEntity}.
 *
 * <p>
 * This is a strictly internal entity of the operational layer. It must never be
 * created
 * or mutated directly through the UI — all interactions must go through the
 * {@link FinanceEventEntity}
 * wrapper (Wrapper Isolation Rule).
 *
 * <p>
 * <b>Zero-Sum Rule:</b> The system must validate that the sum of all origin
 * {@link FinanceLineItemEntity} amounts equals the sum of all destination amounts
 * within this
 * Transaction. Money cannot appear or disappear.
 *
 * <p>
 * A Transaction acts as a technical container: it groups the individual
 * {@link FinanceLineItemEntity}s that represent the atomic movements of value between
 * {@link FinanceNodeEntity}s, ensuring double-entry integrity.
 */
@Entity(name = "FinanceTransaction")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class FinanceTransactionEntity extends BaseEntity {

	/** The date and time at which the financial movement occurred. */
	@NotNull
	public LocalDateTime transactionDate;

	/**
	* The atomic movements of value that make up this transaction.
	*
	* <p>
	* Each {@link FinanceLineItemEntity} links exactly one {@link FinanceNodeEntity} to an
	* amount.
	* The collection of all line items must satisfy the Zero-Sum Rule.
	*
	* <p>
	* Uses {@link LinkedHashSet} to keep insertion order stable while preserving
	* Set semantics. This makes line-item iteration deterministic (UI/DTO order)
	* without replacing the managed collection instance.
	*/
	@OneToMany(mappedBy = "transaction", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
	@Builder.Default
	public Set<FinanceLineItemEntity> lineItems = new LinkedHashSet<>();

}
