package com.mypaybyday.entity;


import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * The accounting envelope generated by an {@link FinanceEvent}.
 *
 * <p>This is a strictly internal entity of the operational layer. It must never be created
 * or mutated directly through the UI — all interactions must go through the {@link FinanceEvent}
 * wrapper (Wrapper Isolation Rule).
 *
 * <p><b>Zero-Sum Rule:</b> The system must validate that the sum of all origin
 * {@link FinanceLineItem} amounts equals the sum of all destination amounts within this
 * Transaction. Money cannot appear or disappear.
 *
 * <p>A Transaction acts as a technical container: it groups the individual
 * {@link FinanceLineItem}s that represent the atomic movements of value between
 * {@link FinanceNode}s, ensuring double-entry integrity.
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table
public class FinanceTransaction extends BaseEntity {

    /** The date and time at which the financial movement occurred. */
    @NotNull
    public LocalDateTime transactionDate;

    /** Timestamp set once when this record is first persisted. Never updated afterwards. */
    @Column(updatable = false)
    public LocalDateTime createdAt;

    /** Timestamp updated every time this record is modified. */
    public LocalDateTime updatedAt;

    /**
     * The atomic movements of value that make up this transaction.
     *
     * <p>Each {@link FinanceLineItem} links exactly one {@link FinanceNode} to an amount.
     * The collection of all line items must satisfy the Zero-Sum Rule.
     */
    @OneToMany(mappedBy = "transaction", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @Builder.Default
    public List<FinanceLineItem> lineItems = new ArrayList<>();

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
