package com.mypaybyday.entity;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * The accounting envelope generated by an {@link FinanceEvent}.
 *
 * <p>
 * This is a strictly internal entity of the operational layer. It must never be
 * created
 * or mutated directly through the UI — all interactions must go through the
 * {@link FinanceEvent}
 * wrapper (Wrapper Isolation Rule).
 *
 * <p>
 * <b>Zero-Sum Rule:</b> The system must validate that the sum of all origin
 * {@link FinanceLineItem} amounts equals the sum of all destination amounts
 * within this
 * Transaction. Money cannot appear or disappear.
 *
 * <p>
 * A Transaction acts as a technical container: it groups the individual
 * {@link FinanceLineItem}s that represent the atomic movements of value between
 * {@link FinanceNode}s, ensuring double-entry integrity.
 */
@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table
public class FinanceTransaction extends BaseEntity {

    /** The date and time at which the financial movement occurred. */
    @NotNull
    public LocalDateTime transactionDate;

    /**
     * The atomic movements of value that make up this transaction.
     *
     * <p>
     * Each {@link FinanceLineItem} links exactly one {@link FinanceNode} to an
     * amount.
     * The collection of all line items must satisfy the Zero-Sum Rule.
     */
    @OneToMany(mappedBy = "transaction", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @Builder.Default
    public List<FinanceLineItem> lineItems = new ArrayList<>();

    @Override
    public String toRagContent() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("Transaction ID %s records a financial movement on %s. ",
                id != null ? id.toString() : "NEW",
                transactionDate));

        if (lineItems != null && !lineItems.isEmpty()) {
            sb.append(String.format("It involves %d atomic line items: ", lineItems.size()));
            String details = lineItems.stream()
                    .map(li -> String.format("%s for %s",
                            li.amount != null ? li.amount : "0",
                            li.financeNode != null ? li.financeNode.name : "unknown"))
                    .collect(java.util.stream.Collectors.joining(", "));
            sb.append(details).append(".");
        } else {
            sb.append("No line items are currently associated with this transaction.");
        }

        return sb.toString();
    }
}
